version: '3.8'

services:
  linka-frontend:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://linka.ufc.br/api/v1
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - linka-network

networks:
  linka-network:
    external: true 