version: '3.8'

services:
  linka-frontend:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - linka-network

networks:
  linka-network:
    external: true 