name: Deploy para Vercel

on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - develop
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{github.ref == 'refs/heads/develop' || github.base_ref == 'develop'}}
    steps:
      - uses: actions/checkout@v2
      - name: Instalar Dependencias
        run: npm ci && npx playwright install --with-deps
      - name: Executar testes
        run: npx playwright test

  build_and_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/release' || github.base_ref == 'release' }}
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        id: vercel-deploy
        with:
          vercel-args: --prod
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
      - name: preview-url
        run: |
          echo ${{ steps.vercel-deploy.outputs.preview-url }}
