name: Deploy para Vercel

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   if: ${{github.ref == 'refs/heads/develop' || github.base_ref == 'develop'}}
  #   permissions:
  #     contents: write
  #     pull-requests: write
  #     repository-projects: write
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: amondnet/vercel-action@v20
  #       id: vercel-deploy
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         vercel-org-id: ${{ secrets.ORG_ID}}
  #         vercel-project-id: ${{ secrets.PROJECT_ID}}
  #     - name: preview-url
  #       run: |
  #         echo ${{ steps.vercel-deploy.outputs.preview-url }}

  build_and_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' || github.base_ref == 'master' }}
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        id: vercel-deploy
        with:
          vercel-args: --prod
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
      - name: preview-url
        run: |
          echo ${{ steps.vercel-deploy.outputs.preview-url }}
